### PR TITLE
Whitespace tagging causing issues with SMS-based services

### PR DESCRIPTION
**Pull request by BastienLQ**
[CallYa Toppings](http://toppings.vodafone.de/)

I am always having problems redeeming my toppings with Vodafone. I already filed that Issue on https://github.com/WhisperSystems/TextSecure/issues/1780, but they were very reluctant to even cope with fixing it. I was wondering if you guys might be a little more open towards this Issue, which very likely does not just happen to be mine?

### CODE REVIEW

**Comment by BastienLQ** [comment]
Now, before adding whitespace tag, the app will check if the number is not too short (< 7 after removing non numeric characters). I don't use `libphonenumber` because it requires a country code.

**Comment by BastienLQ** [comment]
@SecUpwN Can you test the `issue-111` branch?

**Comment by SecUpwN** [comment]
>Can you test the `issue-111` branch? 

I'd love to! Would you please send me a compiled APK of that? I'm currently not able to compile stuff.

**Comment by BastienLQ** [comment]
@SecUpwN You can get a build here: https://files.smssecure.org/SMSSecure-debug-dbbdb34.apk
APK signature is different from F-Droid/Play/Amazon, so you'll need to follow the [migration guide](https://github.com/SMSSecure/SMSSecure#migrating-from-textsecure-to-smssecure).

**Comment by SecUpwN** [comment]
@BastienLQ, I've tested the APK you've linked above and it works beautifully! :+1: 
Thanks to everyone who worked hard on solving this, please merge into `master`.

**Comment by pR0Ps** [comment]
@SecUpwN: Can you test https://files.smssecure.org/SMSSecure-debug-c68a5bc.apk ?

**Comment by SecUpwN** [comment]
@pR0Ps, what is the difference between the first and the second APK?

**Comment by pR0Ps** [comment]
@SecUpwN  A more internationalized method of checking numbers.

**Comment by SecUpwN** [comment]
>A more internationalized method of checking numbers.

Works beautifully over here in Germany.

**Pull request merged**
