### PR TITLE
Mms size and imageresize option

### PR DESCRIPTION
**Pull request by vdveer**
Added option to disable image resizing if your plan allows bigger (sized) images. Also added a slider to change the maximum MMS size. My provider only allows 300kb messages and as the messages unencrypted stay below 280k, encrypted version might sometimes go over 300kb. So I added a slider to configure this limit. 

ps. My first ever android development so might have overseen something in the preferences. Let me know, but seems to work fine.

### CODE REVIEW

**Comment by BastienLQ** [comment]
Thanks for your contribution. But changing the maximum size if MMS is not a good idea. The limit can vary between sender and recipient, so changing it may result in difficulties to receive MMS even if the message has been sent successfully.

**Comment by vdveer** [comment]
I presumed that incoming up to 1MB (that's why I set this as a limit) is allowed. I get messages from different providers with bigger size images, so I believed this was only an issue for outgoing messages. If not, I will try to fix this issue (since encrypted messages can go over the 300k, as the limit is not enforced after wrapping the pdu) in a different way.

**Comment by BastienLQ** [comment]
Max size is for example 300KB on Free Mobile (France).

**Comment by vdveer** [comment]
Here on T-Mobile NL it's 300kB as well, but I remember incoming messages could be larger. I have no set-up to verify this, since both of my phones are on the same provider at the moment.

**Comment by BastienLQ** [comment]
But this is not a standard and it can cause troubles during reception (and complaints) if the providers blocks MMS bigger than 300KB.

**Comment by vdveer** [comment]
The MMS standard doesn't define a maximum size; but due to WAP limitations the default is implicated to be 300kb. When user changes the setting we can warn them about the possible issues when sending messages to a WAP phone (which do have the 300kb incoming limit). But first I will need to check my previous statement of incoming messages the 300kb < size > 1mb. I will post my findings here.
I am not trying to get this code into the master branch, just checking user scenarios since I believe part of the users would like this limit to be configurable.

**Comment by vdveer** [comment]
I didn't get to test the incoming limit yet, but I have coded an addition to SMSsecure in the spare hours this weekend that people might like. The ability to select and send files (or share through other apps) and send over secure conversation (with correct filename). Check out my my experimental (although it's kind of complete for file transfer now) branch https://github.com/vdveer/SMSSecure/tree/experimental_multimms_file_transfer_in_securemode . File mode is to be activated in advanced settings. 
For my own use and just to see if it's easily done, I want to add an option to allow bigger files than the MMSlimit to be send and split up in multiple PDU's.
Let me know if you (two) like it and I can make a pull request without the mms-size-slider commits.

**Comment by vdveer** [comment]
I am not sure if you still get notifications for this thread so in a while I might just open a pull request to discuss the changes / details.

**Comment by BastienLQ** [comment]
Don't worry, we receive notifications even if a PR/issue is closed. But we don't always have a lot of free time. ;-)

**Pull request closed without merging**
