### PR TITLE
LED doesn't blink with encryption enabled

### LINKED ISSUE #261: LED doesn't blink with ecryption enable
Smartphone : Google Nexus 5 & Sony Xperia Z2

Since 0.10.1 LED Notification doens'nt blink when I receive a secure SMS. (just 1 time and no more)
But when I disable encryption for the same contact, LED blinks correctly.

I try to modify LED colors, speed, name of contact but it didn't fix it.

Can you help me ?

### PR DESCRIPTION
**Pull request by BastienLQ**
Fixes #261.

Need to be tested.

### CODE REVIEW

**Comment by BastienLQ** [comment]
Seems to work. @johanw666: did you test it?

**Comment by johanw666** [comment]
With the current versions 0.13..x it works correctly on my device.

**Comment by discworld** [comment]
Hello,

Just to let you know, this commit is meant to fix #203 as well.

Thanks!

**Comment by johanw666** [comment]
Flashing works also correct on my phone with 0.13.2.

**Pull request merged**
