### PR TITLE
Fix up project renaming

### PR DESCRIPTION
**Pull request by BoBeR182**
Seems like some parts of the source code did not get renamed properly, hopefully thing fixes it.

### CODE REVIEW

**Comment by BoBeR182** [comment]
I typed secureSMS instead of SMSsecure

**Comment by BastienLQ** [comment]
`org.whispersystems` is the textsecure library and we do not change it for now. So this package name must not be chnged.

In `src/org/smssecure/smssecure/Release.java`, your changes are related to push messages and this code would be remove in #3.

The only change we can merge is the one in `res/values/google-playstore-strings.xml`.

**Comment by BoBeR182** [comment]
Do you know how to undo all my commits to exclude the non working ones?

**Comment by BastienLQ** [comment]
Just reset to 566dcc55310375423344091d34e9fc0b7ff3f8b3, make your new commit, force push and reopen a pull request.

**Comment by BoBeR182** [comment]
I'm rather new to git and I'm pretty sure I am doing it wrong, do you mind writing out what commands I would have to run to get it to revert back to before I pushed my changes?

**Comment by BastienLQ** [comment]
`git reset --soft HEAD~1` will remove that latest commit. If you want to remove 3 commits, just run `git reset --soft HEAD~3`.
You also can delete your fork, refork SMSSecure and work on this fresh copy.

**Pull request closed without merging**
