### PR TITLE
Attachment drawer refactor

### PR DESCRIPTION
**Pull request by BastienLQ**
Based on #287.
This PR removes the back button (useless since tapping on the background masks the drawer), re-add the camera button (removed in dbe30cf) and refactor the drawer with a transparent background.
Must be merged after #287 and a rebase.

### CODE REVIEW

**Comment by pR0Ps** [comment]
Is is supposed to look like this?

screenshot_2015-12-14-23-09-12

**Comment by pR0Ps** [comment]
Rebased on top of master.

**Comment by BastienLQ** [comment]
I'll reduce space between the two lines of icons.

**Comment by BastienLQ** [comment]
Ready to be merged.

**Comment by pR0Ps** [comment]
I don't think the full-screen overlay is as nice as the list modal (like before) or what upstream has now (the drawer).

Is there any reason we can't just copy upstream and use the drawer?

**Comment by BastienLQ** [comment]
The upstream drawer is a quite ugly with its white background. I think it's to include camera direct capture. I refactored the drawer because we don't have the direct capture functionality.

We could keep the old modal, yes.

**Comment by pR0Ps** [comment]
I just built the upstream today and it seems like they have 2 ways to attach a picture from the camera.

There's a little camera icon in the text field which pulls up the in-app camera drawer thing. There's also a shutter icon in the attach menu which brings up the camera app like we do normally.

I think the drawer thing that they've implemented upstream looks nice in the dark theme (see attached). Maybe we can just change the styling of it for the light theme and keep the code differences from upstream minimal.

screenshot_2015-12-21-15-16-58

**Pull request closed without merging**
