### PR TITLE
Upstream

### PR DESCRIPTION
**Pull request by BastienLQ**
Closes #156.

### CODE REVIEW

**Comment by BastienLQ** [comment]
@pR0Ps Ready to be merged. I'll refactor attachment panel in a new PR.

**Comment by pR0Ps** [comment]
Some issues I'm seeing:

Deleting/archiving
 - Ability to delete a thread while viewing it (from the 3 dot menu) is gone
 - No way to archive the thread while viewing it (same menu)
 - No way to see archived messages (upstream does this from a "view archived messages" menu item).
 - Archiving functionality demo here: https://www.dropbox.com/s/o6bz1okfejuumfq/inbox-textsecure.mov?dl=0

New contact selection view:
 - Scroll bar snaps to top and stays there whenever the view is scrolled.

Didn't test anything to do with MMS since I don't have that capability. There are new things related to playing audio and showing thumbnails of images in the conversation view though so those should be areas to look at closely.

I will keep using this for a bit and see if I come across anything else.

**Comment by BastienLQ** [comment]
You can see archived conversations by tapping on the "Archived conversations" item at the end of the list of conversations.

**Comment by BastienLQ** [comment]
Ready to be merged.

**Comment by pR0Ps** [comment]
Sorry, I didn't notice that option at the bottom. Delete/archive options are present and working in the thread, scroll bar is fixed.

Looks good to me, merging.

**Pull request merged**
