### PR TITLE
Update googleplay links

### PR DESCRIPTION
**Pull request by BoBeR182**
Updated the Google Play links for when we finally get into the Play store.

### CODE REVIEW

**Comment by BastienLQ** [comment]
cc @SMSSecure/devs

**Comment by pR0Ps** [comment]
We're going to have to rework most of this text when we do the actual Play Store submission so we should probably hold off on this until then.

**Comment by BoBeR182** [comment]
@pR0Ps Should I start working on a nice corporate-like Play Store description and etc, I may not be good at coding right now, but would be happy to ease the marketing burden while you guys patch and depushify SMSSecure.

**Comment by BoBeR182** [comment]
Updated a little more of the strings seeing as we are getting ready to push SMSSecure to F-Droid and the Play Store

**Pull request closed without merging**
