### PR TITLE
New Mms API

### PR DESCRIPTION
**Pull request by BastienLQ**
Need to test and to fix a timeout bug on Lollipop.

### CODE REVIEW

**Comment by BastienLQ** [comment]
On Lollipop, it works with unencrypted MMS. Encrypted MMS aren't received (noting in logs). Not tested with other Android versions.

**Comment by BastienLQ** [comment]
Well... It seems to work on Lollipop, in fact.

**Comment by pR0Ps** [comment]
I can't test on Lollipop (no device), could someone else verify this?

**Comment by BastienLQ** [comment]
Actually, MMS aren't encrypted. I'm investing. Tested on CM12 (Lollipop) and CM11.

**Comment by BastienLQ** [comment]
de43926967b806f7ea8187e156bc1c6a74dd853a add MMS encryption for outgoing messages. Ready to merge.

**Pull request merged**
