### PR TITLE
Exporting/importing keys and encrypted SMS database

### PR DESCRIPTION
**Pull request by BastienLQ**
To allow full backup and restore

### CODE REVIEW

**Comment by BastienLQ** [comment]
Seems to work. The only issue I experienced is that a passphrase is asked after the backup, even if none was configured (just quit and relaunch SMSSecure to have access to messages).

**Comment by tuxayo** [comment]
How can we check that the bugs that caused this feature to be disabled are not still here?
https://github.com/WhisperSystems/TextSecure/issues/1705#issuecomment-49261200

**Comment by johanw666** [comment]
As far as I can see all this code does is copy the map /data/data/org.smssecure/smssecure to the (internal) SD card. A symlink in this map to lib, which points to /data/app-lib/org.smssecure.smssecure-2 is copied as a map, which contains only a library (libcurve25519.so). I don't see why this needs to be backuped but I assume it is just done to keep the backup code easy and just copy everything.

Restoring an old backup could lead to problems with sessions of course - but that problem also exists whith a reinstall.

Are there situations where the internal state of the /data/data map is inconsistent? Perhaps changes in the settings that are not immediately saved?

**Comment by tuxayo** [comment]
Is libcurve25519.so portable between all android devices/versions that can run SMSSecure? If not that whould cause problems for migrations.

**Comment by johanw666** [comment]
"Is libcurve25519.so portable between all android devices/versions that can run SMSSecure?"

No. If you open the apk file of TextSecure as a zipfile, you see a map lib, which contains submaps armeabi, armeabi-v7a, mips and x86. They all contain a separate version of this library for different systems. This might indeed cause problems.

**Comment by BastienLQ** [comment]
If you import an encrypted backup to a new phone, you won't be able to read messages (you just have a list). Fingerprint is not saved in the backup: I suppose the bug is located here.

**Comment by pR0Ps** [comment]
I really don't think we should do this. TextSecure removed it because it was unreliable. Why are we re-adding it?

I get that it's a feature that people want, but if it's broken, it shouldn't go into the app. This is especially true since it's a pretty critical operation (it's a backup, people expect it to work).

Alternate suggestion:

Users can already transfer SMS messages using unencrypted backups. The minimum extra required to allow smooth transitions to new devices would be to have an option to transfer the public and private identity keys ("Export identity"?).

Related: Since we never supported encrypted backups and TextSecure doesn't anymore, we should remove the option to import encrypted backups, it's misleading.

**Comment by tuxayo** [comment]
> I get that it's a feature that people want, but if it's broken, it shouldn't go into the app. 

The current implementation is broken, not the feature. If the bug is found and fixed is okay. Or circumvented by using the plain text backup and encrypting it (in a password protected archive for example)

> The minimum extra required to allow smooth transitions to new devices would be to have an option to transfer the public and private identity keys ("Export identity"?).

Indeed, that would be a nice feature to complete the backup/import functionalities

**Comment by BastienLQ** [comment]
I agree, this is an important feature: if you have a new phone, you may not want to restart all of your secure sessions.

**Comment by pR0Ps** [comment]
> The current implementation is broken, not the feature

And re-adding the current implementation is exactly what's being proposed at the moment.

**Comment by tuxayo** [comment]
> And re-adding the current implementation is exactly what's being proposed at the moment.

Yes and I hope the "do not merge" label stays here until the proposal is safe.

Do we even know how trigger/test the bug(s) of the original implementation?

**Comment by BastienLQ** [comment]
We know the code is broken, that's why there is the *do not merge* label: it's a WIP branch. Now, I know what bugs there are in those lines and I can work on fixing them.
So we will keep this feature and fix it. And we don't care about what TS devs want to do.

**Comment by johanw666** [comment]
"Fingerprint is not saved in the backup"

Then where is that fingerprint stored? This backup seems to copy just the /data/data/smssecure map completely; so it has to be stored somewhere else. Copying that directory with Titanium Backup to another device works, that's how I got TextSecure working with a phonenumber I have in a dumbphone: register is on an Android phone, make a TB and restore that on the tablet. Studying the files in the TB that is exactly the same.

**Comment by pR0Ps** [comment]
I think the reason it was disabled in the first place was that it wasn't just a quick fix. In fact, the PR that removes it notes that it was removed ["pending fixes to the major issues around it"](https://github.com/WhisperSystems/TextSecure/pull/1631). If it was easy, they would've just fixed it sometime in the last year since it was removed.

This is why I proposed something that deals with the current "can't change devices" problem without adding back in code with known major issues and trying to band-aid them all.

Suggestion: Instead of trying to do a full backup of everything, allow exporting the critical information (identity keypair), then the first time the user runs the app (where it would usually generate the keypair), ask them if they would like to import an identity or generate a new one. After that, messages can be imported across via some other method (already supported in multiple ways).

**Comment by BastienLQ** [comment]
Backup can be made across devices: I just tested with oandbackup and I can export my messages and my fingerprint on another device without any problem. So it *is* possible to fix that issue.

**Comment by tuxayo** [comment]
> Now, I know what bugs there are in those lines and I can work on fixing them.

By the way, what are the bugs?

**Comment by BastienLQ** [comment]
@tuxayo Keys aren't properly backed up and it results in unusable backups if the phone changes.

**Comment by tuxayo** [comment]
@BastienLQ 
- The keys used in the sessions or are they involved in the database encryption?
- So the backup couldn't be used to switch from a phone to another?

**Comment by BastienLQ** [comment]
Currently, backup will work on the same phone, I suppose on the same installation because messages cannot be decrypted on another phone with the same backup (that's why I suspect a bug in key's backup).

**Comment by tuxayo** [comment]
I understand now!

I'm trying to find what is actually exported and it seems it's basically the whole private app directory.
https://github.com/SMSSecure/SMSSecure/blob/master/src/org/smssecure/smssecure/database/EncryptedBackupExporter.java#L79

That would mean that the keys are somewhere else, that would be the SQLite database of the app right?

**Comment by matlink** [comment]
What is the state of this PR ? Is it available ? Is it pending ?

**Comment by BastienLQ** [comment]
Pending. We're busy for now. But we always accept PR.

**Comment by matlink** [comment]
Okay, any way to backup SMS/MMS to an encrypted file ? Even via command line ? I just want to ensure to be able to recover my SMS/MMS if something bad happens.

**Comment by johanw666** [comment]
I tested a bit more with this code. 

1. I make an encrypted backup using the original code
2. FC SMSSecure fron settings and remove all its data
3. start SMSSecure, go through the welcome screens and read the encrypted backup. Now all messages are unable to decrypt.
4. Go to settings again and FC SMSSecure again.
5. Open SMSSecure, enter your password if you set one, and all messagers are fine. The only thing that happens after import if intent.setAction(KeyCachingService.CLEAR_KEY_ACTION); in ImportFragment.java; that appears to be not enough. The difference between this import and resture via Titanium Backup and similar tools is that they tend to pause or stop SMSSecure when they restore its data, something I simulated with the FC.
6. This still requires to reset all secure sessions if there are messages missing from the backup.

**Comment by johanw666** [comment]
Oh, and I changed in EncryptedBackupExporter.java the export to leave out the library file. I hardcode the filename for this test, I should detect it from somewhere to make this code more robust.

```java
  private static void exportDirectory(Context context, String directoryName) throws IOException {
    File directory       = new File(context.getFilesDir().getParent() + File.separatorChar + directoryName);
    File exportDirectory = new File(getExportDirectoryPath() + File.separatorChar + directoryName);

    if (directory.exists()) {
      exportDirectory.mkdirs();

      File[] contents = directory.listFiles();

      for (int i=0;i<contents.length;i++) {
        File localFile = contents[i];

        if ( localFile.getAbsolutePath().contains("libcurve25519.so")) {
          // JW: the library should not be exported, so do nothing
        } else if (localFile.isFile()) {
          File exportedFile = new File(exportDirectory.getAbsolutePath() + File.separator + localFile.getName());
          migrateFile(localFile, exportedFile);
        } else {
          exportDirectory(context, directoryName + File.separator + localFile.getName());
        }
      }
    } else {
      Log.w("EncryptedBackupExporter", "Could not find directory: " + directory.getAbsolutePath());
    }
  }
```

**Comment by tuxayo** [comment]
If I understand correctly the results of the tests, we need to make the app restart itself after the backup. Then we will be good for some wider testing right?

**Comment by BastienLQ** [comment]
Not exactly. Some files aren't properly saved and/or restored, causing
the issue when SMSSecure tries to decrypt the database in some conditions.

**Comment by tuxayo** [comment]
What are the problematic files? And the conditions to reproduce a restore failure?

**Comment by BastienLQ** [comment]
@tuxayo Switch from a smartphone to another. I suppose a fresh ROM install will do the same.

**Comment by BastienLQ** [comment]
Rebased.

**Comment by BastienLQ** [comment]
Fixed! \o/
Need to be tested and merged after #345 and a rebase.

**Comment by tuxayo** [comment]
> Fixed! \o/
> Need to be tested and merged after #345 and a rebase.

Awesome! I can't wait to try it :)
(on the same phone though...)

**Pull request merged**
