### PR TITLE
Upstream

### PR DESCRIPTION
**Pull request by BastienLQ**

### CODE REVIEW

**Comment by pR0Ps** [comment]
I'm seeing that all outgoing messages have the SMS confirmation checkmark, even ones that didn't before the update. Turning the SMS confirmation off doesn't change anything.

**Comment by BastienLQ** [comment]
Are you sure you're not making a confusion between "sent" and "received"? See 5cca2177664e2e0151545d20986e4070fb7c1c11.
tmp_24693-_20150714_113109482239165

**Comment by BastienLQ** [comment]
Fixed in e43a2ae.

**Comment by pR0Ps** [comment]
Looks good, merging

**Pull request merged**
