### PR TITLE
Remove push-related code

### PR DESCRIPTION
**Pull request by pR0Ps**
There's still some push-related code hanging around in the codebase. Now that push isn't supported, it should be removed to reduce the complexity of the app.

### CODE REVIEW

**Comment by pR0Ps** [comment]
Don't merge this yet, there's still a lot more to go

**Comment by BastienLQ** [comment]
Due to #15, can you rebase your branch?

**Comment by BoBeR182** [comment]
I think I'm just going to delete my fork and redo it? Will that break anything?

**Comment by pR0Ps** [comment]
I'll keep rebasing periodically so it'll be a ff when it goes in.

**Comment by pR0Ps** [comment]
Still a bunch more to do, but this takes out most of it and fixes a bunch of UI things. It should go in now and I'll start another branch to keep removing the rest of it.

**Pull request merged**
